name: binder
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - matplotlib
    - watermark
    - git+https://github.com/goerz-testing/pypkg_bintray_01.git@master#egg=pypkg_bintray_01
